theme: jekyll-theme-cayman
title: Learn Basic Spanish Today
description: explore here
github:
  page2: infonspanishlangnculture.html
  page3: vocabulary.html
  page4: phrases.html
  page5: basicgrammar.html
  page6: listeningandreading.html

