theme: jekyll-theme-cayman
title: Learn Basic Spanish Today
description: explore here
github:
  page2: parttwohomework.html
  page3: vocabulary.html
  page4: grammar.html
  page5: idioms.html
  page6: pagesix.html
